### ISSUE TITLE
item.twig

### ISSUE THREAD

**Issue by diomed** [jgonyea/grav-theme-editorial#8]
RuntimeException (400)
Template "item.html.twig" is not defined.

**Comment by jgonyea** [comment]
Hi, @diomed,
Where are you seeing that message? Thanks!

**Comment by diomed** [comment]
I see it coz you're missing a template that some other themes have, and yours don't.
[For Example](https://github.com/tranduyhung/grav-theme-clean-blog/tree/master/templates)

**Comment by jgonyea** [comment]
Sorry, I meant, what's calling the item twig file. I'll try to get it added soon.

**Comment by diomed** [comment]
it's not an error per se, but when one comes from different theme that has that template, it is.

**Comment by jgonyea** [comment]
Hmm, then I think the issue is more that you switched from a theme that uses that twig definition than it is editorial not having it.  Technically, a theme could implement 100 twig definitions, but I wouldn't expect editorial to support them.  You as the site owner would either need to copy them over or create your own.

Does that make sense, @diomed ?

**Comment by diomed** [comment]
I've used several themes: fact remains that majority of themes available on list of themes on grav site HAS item.twig file.

**Comment by jgonyea** [comment]
Ok, I'll look into it.  Thanks.

**Comment by jgonyea** [comment]
Fixed in 1.0.0
